# Generated by Django 4.0 on 2023-10-31 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_job_dateposted_alter_message_timesent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='DatePosted',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='Timesent',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
