# Generated by Django 4.0 on 2023-10-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_conversation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='DatePosted',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='Timesent',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
